safe:        false
auto:        true
server:      false
server_port: 4000

source:      .
destination: ./_site
plugins:     ./_plugins

future:      true
lsi:         true
pygments:    true
markdown:    rdiscount
permalink:   /:categories/:title
permalink:   /posts/:title

rdiscount:
  extensions: [smart]

name: Jeboot
url: 
title: 
description:   
base:          
author:        
email:         
redirects:     

exclude:    
- ./tasks
- README.md
